### ISSUE TITLE
Skill Package Remote Sync Status is always Out of sync because SMAPI doesn't return ETag

### ISSUE THREAD

**Issue by vpoluyaktov** [alexa/ask-toolkit-for-vscode#111]
**Describe the bug**

i'm not sure is it the extension or Amazon SMAPI bug but my skill package is always Out of Sync. Even if I run Export skill package it's still Out of Sync.

I tried to debug the extension code and found that **SMAPI _GET /v1/skills/exports/{exportId}_** call returns a response with no eTag field. According to the doc: https://developer.amazon.com/en-US/docs/alexa/smapi/skill-package-api-reference.html#get-export-status the response should be:

Example response body
```
{
  "skill": {
    "expiresAt": "1550521786056",
    "location": "URL to download the exported skill",
    "eTag": "string"
  },
  "status": "SUCCEEDED"
}
```

but I get only **expiresAt** and **location**. No **eTag**.

![Screen Shot 2021-03-19 at 12 18 16](https://user-images.githubusercontent.com/1992836/111832810-7a271200-88ae-11eb-9dcb-970f35255755.png)

As result of this **getSkillPackageSyncStage** method always return **outOfSync** status:

![Screen Shot 2021-03-19 at 12 18 48](https://user-images.githubusercontent.com/1992836/111832962-ae9ace00-88ae-11eb-9332-6135b0a5bb28.png)

OS: Darwin x64 20.3.0
Visual Studio Code Version:  1.54.3
Alexa Skills Toolkit Version: 2.4.0
Git Version: git version 2.21.0

Please advise

**Comment by mbtd-dev** [comment]
I had no issues a few days back, but I think this is what is suddenly happening to me too when using VSCode, I am simply unable to sync my skill package and keep having to "force deploy" to get by. 

Here's some further info from the ask tool output when I try to sync by exporting the skill package:

```
[verbose - 2021-03-19 20:04:48.444Z] Calling method: downloadSkillPackage, args: ["https://skill-exports-prod-na.s3.amazonaws.com/amzn1.ask-package.export.[redacted]","[redacted]/skill-package",true]
[verbose - 2021-03-19 20:04:50.131Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-03-19 20:04:50.131Z] Calling method: getAskResourceConfig 
[debug - 2021-03-19 20:04:50.134Z] skill-package/skillPackage.zip is not following the correct format of skill-package structure,
            thus it won't be consumed at service side. Please follow [this guide](https://developer.amazon.com/en-US/docs/alexa/smapi/skill-package-api-reference.html#skill-package-format) to upgrade your skill-package folder structure. For more detailed skill-package format, please check .ask/schema/skillPackageSchema.json. 
[verbose - 2021-03-19 20:04:50.338Z] Calling method: unzipFile, args:  ["[redacted]/skill-package/skillPackage.zip","[redacted]/skill-package",true,true]
[verbose - 2021-03-19 20:04:50.350Z] Calling method: ask.exportSkillPackage.setAskState, args: [{"$mid":1,"fsPath":"[redacted","path":"[redacted]","scheme":"file"},null]
[error - 2021-03-19 20:04:50.350Z] Fail to fetch the skill package eTag. 
```

**Comment by vpoluyaktov** [comment]
I see this error too. I had to unzip skillPackage.zip manually

**Comment by Chih-Ying** [comment]
Hi @vpoluyaktov  and @mbtd-dev

Thank you for the report. Sorry for the inconvenience.
It is a SMAPI service issue, we have brought it to the service team.

**Comment by Chih-Ying** [comment]
The issue has been resolved, the SMAPI API response contains eTag.
I will close this issue report. Please let me know if there are any problems. Thank you!
