### ISSUE TITLE
Typescript deploy to lambda

### ISSUE THREAD

**Issue by andrelandgraf** [alexa/ask-toolkit-for-vscode#118]
**Desktop (please complete the following information):**

-   OS: Mac Catalina 10.15.07
-   VS Code version: .54.3
    - Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
    - Date: 2021-03-15T11:57:12.728Z (2 wks ago)
    - Electron: 11.3.0
    - Chrome: 87.0.4280.141
    - Node.js: 12.18.3
    - V8: 8.7.220.31-electron.0
    - OS: Darwin x64 19.6.0
-   Alexa Skill Toolkit extension version: v2.5.0

**Question**

I migrated my skill to Typescript. I have trouble updating the location of index.handler using the Alexa Skills Toolkit. I am using the Alexa Console built-in repository, lambda function, and cloud watch. 

My code looks very similar to [this sample skill](https://github.com/alexa/skill-sample-nodejs-audio-player/tree/mainline/single-stream). But they are not using the Alexa Skills Toolkit, so I am not sure how to integrate Typescript using the Toolkit.

My folder structure looks like follows:

- > .ask
- > .vscode
- > lambda
    - > dist
        - > src
        - **index.js**
        - index.js.map
    - > node_modules
    - > src
        - > utils
        - > types
        - > data
    - **index.ts**
    - package.json
    - tsconfig.json
- > skill-package
    - > assets
    - > interactionModels
    - skill.json
- .gitignore

Package.json currently points to `"main": "dist/index.js",`. When I upload the project to Alexa Console using the vs code plugin, the code viewer shows me the following code structure:

- > Skill Code
    - > lambda
        - > dist
        - index.ts
        - package.json
        - tsconfig.json
        - > src

I receive the following error on Cloud Watch when I try to call my skill

```
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.handler is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.handler is undefined or not exported",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)",
        "    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"
    ]
}
```

Do I need to even add `dist/` to the lambda or should I add it to `.gitignore`?

What's the best way to solve this issue using not `aws` commands but the plugin or the ask-cli. I am not hosting the lambda on my own and I am also not zipping the code but I deploy it using the Alexa Skills Toolkit. I could migrate to custom lambda and write myself a custom zip command but I would rather stick to the vs code plugin. Unsure how to proceed.

Thanks for your help!

**Comment by andrelandgraf** [comment]
I was able to make it work now. 

- I added the `dist` folder to git and deploy it to lambda using Alexa Skills Toolkit
- I added a `index.js` inside `lambda/` which just looks like follows:

```
const handler = require('./dist/index')

exports.handler = handler
```

Is this how TypeScript is supposed to work with Alexa Skills Toolkit or is there a better way to configure it?

**Comment by nikhilym** [comment]
Hey @andrelandgraf , sorry for the late response. So as you may already know, the `Alexa Console built-in repository` is just the normal AWS Lambda function over an AWS CodeCommit repository for the skill, handled by the Hosted skills service. AWS Lambda doesn't currently support Typescript out of the box, and the developers are expected to build the `.ts` files to `.js` files before uploading to the service. This is the reason why you would still need to upload the `dist` directory containing the `js` files. 

Additionally, the default handler location for the AWS Lambda function for the hosted skills service is `index.handler` and at the moment, that service doesn't provide a way to configure this handler through the tools. This is the reason why you would have to re-import the handler from `dist/index` and export it back again, in your workaround. You can also configure your `tsconfig.json` to output the built files to the same `lambda` folder, and hence not do such workarounds. However, that would add both `js` and `ts` files in the same folder, leading to confusion and maintainability issues. I think your workaround is a good one, until the hosted skill service provides a way to configure the handler location.

As for the sample skill, it seems to have been built on the `ask cli v1` structure. If so, skill devs can use [this migration guide](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html), to convert it to the `ask cli v2` structure, which is compatible with the `ASK Toolkit` vscode extension. Hope this helps.

I am going ahead and closing this issue, considering you are unblocked at the moment. Please create an issue in case you have further questions or have any feedback on the extension. Thanks.

**Comment by andrelandgraf** [comment]
Thanks @nikhilym for the in-depth explanations! This cleared up a lot of assumptions I made. Great to hear that you recommend my workaround for now.
