### ISSUE TITLE
Error when using simulator with virtual device

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-toolkit-for-vscode#121]
**Describe the bug**

After successfully registering a virtual device with the toolkit when I try to type and send any utterance in the toolkit simulator I get this message:
¨The simulator did not respond to your request. Try again.. Reason: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined¨

**To Reproduce**

1. Create your device in the AVS console
2. Register the device in the toolkit
3. Open the simulator in the toolkit and type an utterance (then hit Send)

**Extension Logs**

**Expected behavior**

The simulator should provide a response from Alexa

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Ubuntu 21
-   Visual Studio Code Version: 1.55.2
-   Alexa Skill Toolkit Version: 2.5.0

**Additional context**

**Comment by wyajunjun** [comment]
@germanviscuso Hi, thanks for raising this issue. I reproduced this and it showed the right thing for the utterances, it seems an edge case error. Could you provide more details to help locate the issue?
1. Can you see the `Device` info besides `ASK Profile` in the status bar( at the bottom of toolkit)?
2. What utterance did you input and got this error? Did it happen once or always?
3. Do you try other utterances or skills?
