### ISSUE TITLE
Test Skill / Simulator goes blank

### ISSUE THREAD

**Issue by escarrg** [alexa/ask-toolkit-for-vscode#123]
**Describe the bug**

When using the Skill Simulation window, after sending the first utterance to the skill, the window goes completely blank and cannot type a second one or view the JSON Input or Output other than the debug console.  

**To Reproduce**

1. Open Test Skill > Open Simulator
2. Enter an utterance and click Send 

**Extension Logs**

[debug - 2021-05-06 16:52:30.417Z] Calling method: askContainer.skillsConsole.simulateSkill 
[debug - 2021-05-06 16:52:30.418Z] Calling method: simulateSkill.getHtmlForView 
[debug - 2021-05-06 16:52:30.418Z] Calling method: simulateSkill.checkSimulatorMode 
[debug - 2021-05-06 16:52:30.418Z] Calling method: renderView, args:  [{"name":"simulateSkill","js":true,"args":{"simulateCss":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}}]
[debug - 2021-05-06 16:52:30.418Z] Calling method: interpolate, args:  [{"simulateCss":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}]
[debug - 2021-05-06 16:52:30.458Z] Calling method: renderView, args:  [{"name":"simulateSkill","js":true,"args":{"simulateCss":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}}]
[debug - 2021-05-06 16:52:30.459Z] Calling method: interpolate, args:  [{"simulateCss":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}]
[debug - 2021-05-06 16:52:30.839Z] Calling method: simulateSkill.onReceiveMessageListener 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getSkillDetailsFromWorkspace 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getSkillFolderInWs 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: doesWorkSpaceExist 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getAskState 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillManifestFromWorkspace 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillNameFromLocales, args: [{"en-US":{"description":"Sample Full Description","examplePhrases":["Alexa open hello world","hello","help"],"keywords":[],"name":"MyInsuranceCompany","summary":"Sample Short Description"}},null]
[verbose - 2021-05-06 16:52:30.840Z] Calling method: simulateMessageHelper.handleSkillStatusMessageFromWebview 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: simulateSkillHelper.checkSkillStatus 
[debug - 2021-05-06 16:52:30.840Z] Calling method: simulateSkill.onReceiveMessageListener 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillDetailsFromWorkspace 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillFolderInWs 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: doesWorkSpaceExist 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskState 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillManifestFromWorkspace 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillNameFromLocales, args: [{"en-US":{"description":"Sample Full Description","examplePhrases":["Alexa open hello world","hello","help"],"keywords":[],"name":"MyInsuranceCompany","summary":"Sample Short Description"}},null]
[verbose - 2021-05-06 16:52:30.840Z] Calling method: simulateMessageHelper.handleLocaleMessageFromWebview 
[verbose - 2021-05-06 16:52:31.172Z] Calling method: simulateMessageHelper.getInvocationName 
[debug - 2021-05-06 16:52:34.890Z] Calling method: simulateSkill.onReceiveMessageListener 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: getSkillDetailsFromWorkspace 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: getSkillFolderInWs 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: doesWorkSpaceExist 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getAskState 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getSkillManifestFromWorkspace 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getSkillNameFromLocales, args: [{"en-US":{"description":"Sample Full Description","examplePhrases":["Alexa open hello world","hello","help"],"keywords":[],"name":"MyInsuranceCompany","summary":"Sample Short Description"}},null]
[verbose - 2021-05-06 16:52:34.891Z] Calling method: simulateMessageHelper.handleUtteranceMessageFromWebview 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: simulateSkillHelper.getSimulationResponse, args:  ["open octank insurance"]
[verbose - 2021-05-06 16:52:35.146Z] Retrying simulation request, attempt: 1 
[error - 2021-05-06 16:52:35.337Z] Simulation in progress. 

[verbose - 2021-05-06 16:52:35.838Z] Retrying simulation request, attempt: 2 
[error - 2021-05-06 16:52:36.044Z] Simulation in progress. 

[verbose - 2021-05-06 16:52:37.045Z] Retrying simulation request, attempt: 3 
[error - 2021-05-06 16:52:37.230Z] Simulation in progress. 

[verbose - 2021-05-06 16:52:39.234Z] Retrying simulation request, attempt: 4 
[verbose - 2021-05-06 16:52:39.431Z] Calling method: simulateSkillHelper.formatAlexaResponse 

**Expected behavior**

Skill simulation window should not blank out.

**Screenshots**

**Desktop (please complete the following information):**

OS: Darwin x64 20.4.0 (Big Sur 11.3)
Visual Studio Code Version:  1.56.0
Alexa Skills Toolkit Version: 2.5.0
Git Version: git version 2.31.1

**Additional context**

Tried downgrading to ASK 2.4 but the issue is the same. This used to work about a month ago. May have to do with the VS Code version.

**Comment by escarrg** [comment]
Can confirm that downgrading to VS Code's March 2021 version 1.55.2 works great. It's April 2021's version 1.56.0 that's causing some issue here.

**Comment by digitaltoast** [comment]
Same here - same versions of everything, problem happened since updating vscode to 1.56.0

**Comment by nikhilym** [comment]
Hey @escarrg , @digitaltoast sorry for responding late to the issue and thanks for getting this to our notice. I could reproduce this issue on the latest vscode v1.56.x , while it seems to be working as expected in the earlier version. Will debug and raise a fix soon. In the mean time, if it's not a hassle, we suggest you to use the earlier vscode v1.55.x version for your skill development. Thanks.

**Comment by escarrg** [comment]
Thanks @nikhilym, totally fine and just did a demo using the older version, all good and thank you for looking into it!
