### ISSUE TITLE
Alexa: About Alexa Skills Toolkit

### ISSUE THREAD

**Issue by hindicator** [alexa/ask-toolkit-for-vscode#128]
Hey,
Can't Login to Alexa account with VisualStudioCode plugin.
After click Login, it change to Grey screen and not giving any other feedback.
Another question if I may,
I've bought xiaomi smart bulb and I want to configure it with sdk any python,
Could you give me any good information resource to do it locally instead of through WAN ?
Already have functional code with all the commands I need - turn on, off, brightness strength.
Thanks.

**Comment by nikhilym** [comment]
Hey @hindicator 

> Can't Login to Alexa account with VisualStudioCode plugin.
> After click Login, it change to Grey screen and not giving any other feedback.

This is a duplicate issue. Please check #124 . Please install the latest version `v2.6.0` of the toolkit, and let us know if you are still facing issues.

> I've bought xiaomi smart bulb and I want to configure it with sdk any python, Could you give me any good information resource to do it locally instead of through WAN ?

Unrelated to the toolkit. Please check the developer forums or developer slack channel for support. 

Closing this.
