### ISSUE TITLE
git problem while creating skill

### ISSUE THREAD

**Issue by Yevgeniyk** [alexa/ask-toolkit-for-vscode#129]
**Describe the bug**

I tried to create a new skill 
**To Reproduce**
try to create a skill

**Extension Logs**

**Expected behavior**

Skill to be created

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Windows
-   Visual Studio Code Version: Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
-   Alexa Skill Toolkit Version: 2.5.0

**Comment by nikhilym** [comment]
@Yevgeniyk thanks for raising the issue. Can you please switch the debugging to `verbose` level, and provide the debug output when you try to create the skill? It can help us understand what is causing the issues. Also please check our FAQ section and make sure that you have the latest `git` version installed. Thanks.

**Comment by nikhilym** [comment]
> verbose level in extension?

Yes. Sorry about not being clear. Please switch the debugging level to `verbose` in the extension settings panel, under `ASK Toolkit` & provide us with the logs. Thanks.

**Comment by Yevgeniyk** [comment]
{
    "askToolkit.logLevel": "verbose"
}

in GIT log
Open repository: t:\Projects\Alexa\test\TestSkill3
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref
--format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)
refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
%(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
warning: invalid credential line: Failed to fetch a LWA access token.
fatal: Authentication failed for '
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2/
'

In ask toolkit
[info - 2021-06-02 17:01:57.920Z] Activating extension
[debug - 2021-06-02 17:01:57.921Z] Registering commands in the extension
[debug - 2021-06-02 17:01:57.923Z] Registering views in the extension
[debug - 2021-06-02 17:01:57.923Z] Registering event handlers in the extension
[debug - 2021-06-02 17:01:57.924Z] Registering statusbar in the extension
[verbose - 2021-06-02 17:01:57.925Z] Updating profile icon in the extension
[debug - 2021-06-02 17:01:57.925Z] Registering treeviews in the extension
[verbose - 2021-06-02 17:01:57.947Z] Calling method: findSkillFolders
[debug - 2021-06-02 17:01:57.987Z] Calling method: c.getChildren
[debug - 2021-06-02 17:01:57.995Z] Calling method: l.getChildren
[verbose - 2021-06-02 17:01:57.995Z] Calling method: l.addRootResources
[verbose - 2021-06-02 17:01:57.996Z] Calling method: c.addRootResources
[debug - 2021-06-02 17:01:57.996Z] Calling method: l.getTreeItem
[debug - 2021-06-02 17:01:57.996Z] Calling method: l.getTreeItem
[debug - 2021-06-02 17:01:57.996Z] Calling method: c.getTreeItem
[debug - 2021-06-02 17:01:57.996Z] Calling method: c.getTreeItem
[debug - 2021-06-02 17:01:57.996Z] Calling method: c.getTreeItem
[debug - 2021-06-02 17:01:58.496Z] Checking if extension version is latest
[debug - 2021-06-02 17:02:00.775Z] Calling method: ask.new
[debug - 2021-06-02 17:02:00.776Z] Calling method: createSkill.getHtmlForView
[debug - 2021-06-02 17:02:00.776Z] Calling method: renderView, args:
[{"name":"createSkill","js":true,"customCss":{"$mid":1,"path":"/vscode-resource/file///c:/Users/Yevgeniy/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.6.0/media/createSkill/createSkill.css","scheme":"https","authority":"
76ddc89c-2fc2-4348-8168-6a089704d21d.vscode-webview-test.com"}}]
[debug - 2021-06-02 17:02:01.945Z] Failed to upload telemetry data.
[debug - 2021-06-02 17:02:21.124Z] Calling method:
createSkill.onReceiveMessageListener
[debug - 2021-06-02 17:02:34.745Z] Calling method:
createSkill.onReceiveMessageListener
[verbose - 2021-06-02 17:02:34.746Z] Calling method:
createSkill.authenticateNewUser
[verbose - 2021-06-02 17:02:35.364Z] Calling method:
createSkill.createSkillFolder, args:
["t:\\Projects\\Alexa\\test","TestSkill3"]
[verbose - 2021-06-02 17:02:35.365Z] Calling method:
createSkill.createNonHostedSkillFlow, args:  ["Yk vs
profile",{"skillName":"TestSkill3","runtime":"NODE_10_X","language":"NodeJS","locale":"en-US","skillFolder":"t:\\Projects\\Alexa\\test","region":"US_EAST_1","isHostedSkill":true},{"$mid":1,"path":"/t:/Projects/Alexa/test/TestSkill3","scheme":"file"},true]
[debug - 2021-06-02 17:02:35.366Z] Calling method: renderView, args:
[{"name":"createInProgress","errorMsg":"Skill creation in
progress..."}]
[verbose - 2021-06-02 17:02:35.368Z] Calling method: createSkill,
args:  [{"skillName":"TestSkill3","runtime":"NODE_10_X","language":"NodeJS","locale":"en-US","skillFolder":"t:\\Projects\\Alexa\\test","region":"US_EAST_1","isHostedSkill":true},{"_proxy":{},"_handle":2}]
[verbose - 2021-06-02 17:02:35.368Z] Calling method: createSkill,
args:  [{"skillName":"TestSkill3","runtime":"NODE_10_X","language":"NodeJS","locale":"en-US","skillFolder":"t:\\Projects\\Alexa\\test","region":"US_EAST_1","isHostedSkill":true},{"_proxy":{},"_handle":2,"_value":{"increment":15,"message":"Creating
an Alexa hosted
skill..."},"$throttle$result$throttledReport":{},"$throttle$lastRun$throttledReport":1622653355368}]
[verbose - 2021-06-02 17:02:35.368Z] Calling method: createManifest,
args:  ["TestSkill3","en-US"]
[verbose - 2021-06-02 17:02:35.704Z] Calling method:
_pollSkillCreation, args:
["amzn1.ask.skill.a8fe8756-6b8d-472d-91b8-cdd1c50952b2"]
[verbose - 2021-06-02 17:02:35.704Z] retrying skill creation polling,
attempt: 1
[verbose - 2021-06-02 17:02:35.886Z] skill not yet created
[error - 2021-06-02 17:02:35.886Z] skill not yet created.

[verbose - 2021-06-02 17:02:38.148Z] retrying skill creation polling,
attempt: 2
[verbose - 2021-06-02 17:02:38.403Z] skill not yet created
[error - 2021-06-02 17:02:38.403Z] skill not yet created.

[verbose - 2021-06-02 17:02:42.361Z] retrying skill creation polling,
attempt: 3
[verbose - 2021-06-02 17:02:42.626Z] skill not yet created
[error - 2021-06-02 17:02:42.626Z] skill not yet created.

[verbose - 2021-06-02 17:02:48.160Z] retrying skill creation polling,
attempt: 4
[verbose - 2021-06-02 17:02:48.461Z] skill not yet created
[error - 2021-06-02 17:02:48.461Z] skill not yet created.

[verbose - 2021-06-02 17:02:54.611Z] retrying skill creation polling,
attempt: 5
[verbose - 2021-06-02 17:02:54.887Z] skill not yet created
[error - 2021-06-02 17:02:54.887Z] skill not yet created.

[verbose - 2021-06-02 17:03:02.172Z] retrying skill creation polling,
attempt: 6
[verbose - 2021-06-02 17:03:02.439Z] skill not yet created
[error - 2021-06-02 17:03:02.439Z] skill not yet created.

[verbose - 2021-06-02 17:03:09.811Z] retrying skill creation polling,
attempt: 7
[verbose - 2021-06-02 17:03:10.077Z] skill not yet created
[error - 2021-06-02 17:03:10.077Z] skill not yet created.

[verbose - 2021-06-02 17:03:17.574Z] retrying skill creation polling,
attempt: 8
[verbose - 2021-06-02 17:03:17.854Z] skill not yet created
[error - 2021-06-02 17:03:17.854Z] skill not yet created.

[verbose - 2021-06-02 17:03:26.487Z] retrying skill creation polling,
attempt: 9
[verbose - 2021-06-02 17:03:26.785Z] skill not yet created
[error - 2021-06-02 17:03:26.785Z] skill not yet created.

[verbose - 2021-06-02 17:03:43.473Z] retrying skill creation polling,
attempt: 10
[verbose - 2021-06-02 17:03:43.816Z] Calling method: cloneSkill, args:
 ["amzn1.ask.skill.a8fe8756-6b8d-472d-91b8-cdd1c50952b2","TestSkill3",{"_proxy":{},"_handle":2,"_value":{"increment":15,"message":"Skill
created. Cloning into the selected
folder..."},"$throttle$result$throttledReport":{},"$throttle$lastRun$throttledReport":1622653423816}]
[verbose - 2021-06-02 17:03:43.816Z] Calling method:
generateSmapiResource, args:
["amzn1.ask.skill.a8fe8756-6b8d-472d-91b8-cdd1c50952b2","TestSkill3"]
[verbose - 2021-06-02 17:03:44.256Z] Calling method: cloneSkill, args:
 [{"_proxy":{},"_handle":2,"_value":{"increment":15,"message":"Skill
created. Cloning into the selected
folder..."},"$throttle$result$throttledReport":{},"$throttle$lastRun$throttledReport":1622653423816}]
[verbose - 2021-06-02 17:03:44.256Z] Calling method: checkGitInstallation
[verbose - 2021-06-02 17:03:44.256Z] Calling method: isGitInstalled
[verbose - 2021-06-02 17:03:44.256Z] Executing git command : git --version
[verbose - 2021-06-02 17:03:44.326Z] Calling method: setupGitFolder
[verbose - 2021-06-02 17:03:44.537Z] Calling method:
downloadGitCredentialScript, args:
["t:\\Projects\\Alexa\\test\\TestSkill3"]
[verbose - 2021-06-02 17:03:44.538Z] Executing git command : git init
"t:\Projects\Alexa\test\TestSkill3" --quiet
[verbose - 2021-06-02 17:03:44.635Z] Executing git command : git
config --local credential.
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2.helper
 ""
[verbose - 2021-06-02 17:03:44.713Z] Executing git command : git
config --local --add credential.
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2.helper
 "!'C:\Users\Yevgeniy\.ask\scripts\git-credential-helper' Yk vs
profile amzn1.ask.skill.a8fe8756-6b8d-472d-91b8-cdd1c50952b2"
[verbose - 2021-06-02 17:03:44.792Z] Executing git command : git
config --local credential.
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2.UseHttpPath
 true
[verbose - 2021-06-02 17:03:44.880Z] Executing git command : git
remote add origin
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2

[verbose - 2021-06-02 17:03:45.404Z] Calling method: getOrInstantiateGitApi
[error - 2021-06-02 17:04:18.151Z] Git folder setup failed for
t:\Projects\Alexa\test\TestSkill3. Reason: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "AuthenticationFailed",
  "gitCommand": "fetch",
  "stdout": "",
  "stderr": "warning: invalid credential line: Failed to fetch a LWA
access token.\nfatal: Authentication failed for '
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2/
'\n"
}

[error - 2021-06-02 17:04:18.151Z] Failed to create a hosted skill.
Reason: Git folder setup failed for t:\Projects\Alexa\test\TestSkill3.
Reason: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "AuthenticationFailed",
  "gitCommand": "fetch",
  "stdout": "",
  "stderr": "warning: invalid credential line: Failed to fetch a LWA
access token.\nfatal: Authentication failed for '
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2/
'\n"
}

[error - 2021-06-02 17:04:18.155Z] Skill creation failed. Reason:
Failed to create a hosted skill. Reason: Git folder setup failed for
t:\Projects\Alexa\test\TestSkill3. Reason: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "AuthenticationFailed",
  "gitCommand": "fetch",
  "stdout": "",
  "stderr": "warning: invalid credential line: Failed to fetch a LWA
access token.\nfatal: Authentication failed for '
https://git-codecommit.us-east-1.amazonaws.com/v1/repos/a8fe8756-6b8d-472d-91b8-cdd1c50952b2/
'\n"
}

[debug - 2021-06-02 17:04:19.155Z] Failed to upload telemetry data.
[debug - 2021-06-02 17:06:45.446Z] Calling method:
createSkill.onViewChangeListener
[debug - 2021-06-02 17:06:53.789Z] Calling method:
createSkill.onViewChangeListener

**Comment by Yevgeniyk** [comment]
Any news?

Yk

**Comment by zyi103** [comment]
Failed to execute git {
  "exitCode": 1,
  "gitCommand": "checkout",
  "stdout": "",
  "stderr": "error: pathspec 'prod' did not match any file(s) known to git.\n"
} 


I'm having similar error

**Comment by zynth666** [comment]
Any more info on this? Trying to onboard a team member and they get this exact error "warning: invalid credential line: Failed to fetch a LWA access token."

Or are there any workarounds? Any help would be greatly appreciated.

**Comment by zynth666** [comment]
OK, weird thing, the problem disappeared. Could this be related to changes made in the alexa developer console taking their time to propagate? Anyways, maybe the extension could return a more understandable error code so we have to do no guesswork.

**Comment by jallwork** [comment]
I'm getting the same problem. 
I try to create a skill using Toolbox. It says it creates the skill and clones in to the selected folder, then it asks for username and password (why? for what ? Alexa? git?)

username
Git:https//git-codecommit.us-east-1.amazonaws.com/v1/repos/lotsOfDigits (Press 'Enter' to confirm or 'Escape' to cancel)
(I press Enter)
password (ditto)

and then it fails. error is:

Skill creation failed. Reason: Failed to create a hosted skill. Reason: Git folder setup failed for c:\Users\john\Documents\Alexa\localdebugthree. Reason: Failed to execute git { "exitCode": 128, "gitErrorCode": "AuthenticationFailed", "gitCommand": "fetch", "stdout": "", "stderr": "warning: invalid credential line: Failed to fetch a LWA access token.\nfatal: Authentication failed for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/LotsOfDigits/'\n" }

I have created a new  VS profile and authenticated with Amazon, which didn't help and created a new Token with Git

VS code help gives:
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No

**Comment by doiron** [comment]
We just published an update to the following script ```~/.ask\scripts\git-credential-helper```.  which solves one case producing this error.  When the following file ```~/.ask/cli_config``` was written with "token" as not the first JSON element within the Profile used.  i.e  if you are using "default" profile, then this file would have worked 

```
{
  "profiles": {
    "default": {
      "token": {                            <<<-- here token is the first item: this was expected
        "refresh_token": "<refreshToken>",
        ...
      },
      "aws_profile": "default"
    }
  },
  "machine_id": "<machineId>"
}
```

but this one would have given you this LWA error ```invalid credential line: Failed to fetch a LWA ... Authentication failed...```

```
{
  "profiles": {
    "default": {,
      "aws_profile": "default",            <<<-- here token is not the first item: you'll need the updated script for this to work
      "token": {
        "refresh_token": "<refreshToken>",
        ...
      }
    }
  },
  "machine_id": "<machineId>"
}
```

you can try to rename ```~/.ask\scripts\git-credential-helper``` as backup i.e. ```~/.ask\scripts\git-credential-helper.old```  and see if retrying to clone a skill will pull it back down from S3 and work, if that was your issue? 

Alternatively, there were some cases where antivirus like AVG were causing problems with that script, treating it as malware or sth. the only solution we found were to uninstall the antivirus. while that could work, we are not suggesting you uninstall the antivirus, a better approach would be to add the script to an allow list if the software supports such configurations.  

Let me know if these don't solve your issue. thanks

**Comment by jallwork** [comment]
My solution was to uninstall AVG (not just disable it) and it works fine. I had the same problem with Avast (unsurprisingly). 
I rely on Windows anti virus now and it works.
I would try your solution, but I will have reinstall AVG.
Thanks for your help
