### ISSUE TITLE
ASK 2.6.0 VSCode 1.56.2 - JSON responses in skill I/O window always empty

### ISSUE THREAD

**Issue by digitaltoast** [alexa/ask-toolkit-for-vscode#133]
### EDIT: Working now... It might have been a dodgy graphics driver?!
Many people are having problems with the latest Nvidia driver, and I just downgraded mine, rebooted, and now I notice that the I/O display is back. What I should have done before was to try a "select all" in the space to see if the text was actually there, but just the same as the background. That is all I can think of, as nothing else that I can see has changed.

Will leave this open for 24 hours in case anyone else has the same...

-------------------------

**Describe the bug**

Since the update to fix the previous bug, the emulator window is not black now, but there is no JSON input or output in the Skill I/O wndows.

**To Reproduce**

Type "open my skill name" in "talk to Alexa" column. 

**Extension Logs**

```
[debug - 2021-06-10 08:45:26.427Z] Calling method: simulateSkill.onReceiveMessageListener 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getSkillDetailsFromWorkspace 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getSkillFolderInWs 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: doesWorkSpaceExist 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getAskResourceConfig 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getAskState 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getSkillManifestFromWorkspace 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getAskResourceConfig 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: getSkillNameFromLocales, args: [XXX]
[verbose - 2021-06-10 08:45:26.427Z] Calling method: simulateMessageHelper.handleUtteranceMessageFromWebview 
[verbose - 2021-06-10 08:45:26.427Z] Calling method: simulateSkillHelper.getSimulationResponse, args:  ["open test skill"]
[verbose - 2021-06-10 08:45:26.710Z] Retrying simulation request, attempt: 1 
[error - 2021-06-10 08:45:26.895Z] Simulation in progress. 

[verbose - 2021-06-10 08:45:27.395Z] Retrying simulation request, attempt: 2 
[error - 2021-06-10 08:45:27.570Z] Simulation in progress. 

[verbose - 2021-06-10 08:45:28.571Z] Retrying simulation request, attempt: 3 
[error - 2021-06-10 08:45:28.754Z] Simulation in progress. 

[verbose - 2021-06-10 08:45:30.754Z] Retrying simulation request, attempt: 4 
[verbose - 2021-06-10 08:45:30.945Z] Calling method: simulateSkillHelper.formatAlexaResponse 
```

**Expected behavior**

JSON input and output windows are populated

**Desktop (please complete the following information):**

-   OS: VSCode running on Win10, but using Remote Explorer on VSCode on Ubuntu LTS 20.04.1
-   Visual Studio Code Version: 1.56.2
-   Alexa Skill Toolkit Version: 2.6.0

**Additional context**

All I can be sure of is that it was working before the "black emulator window" problem  (https://github.com/alexa/ask-toolkit-for-vscode/issues/123 now fixed). In other respects, Skill operates correctly, and I can see the info passing in the debug console.

**Comment by ioanapop** [comment]
I'm seeing the same thing on a VM
