### ISSUE TITLE
Git credentials failed

### ISSUE THREAD

**Issue by krsmga** [alexa/ask-toolkit-for-vscode#135]
I'm having problems cloning the project using Windows. I'm the most current version of vscode and GIT. Everything seems to work, I can log into the amazon account. However, credential management seems to fail. When I try to download the project, during cloning it asks for a username and password and I don't know what to put, and I really shouldn't. I've tried everything, I've reinstalled everything and nothing works. I did a test on the iMac, and it works on the first try. Only in windows no. I don't know what else to do, can anyone help me.

-----------

[debug - 2021-07-01 11:35:55.203Z] Calling method: ask.container.viewAllSkills 
[verbose - 2021-07-01 11:35:55.203Z] Calling method: ask.container.viewAllSkills.skillsQuickPick 
[verbose - 2021-07-01 11:35:55.203Z] Calling method: ask.container.viewAllSkills.checkAndSetQpItems, args: [{"_extensionId":{"value":"ask-toolkit.alexa-skills-kit-toolkit","_lower":"ask-toolkit.alexa-skills-kit-toolkit"},"_id":3,"_visible":true,"_expectingHide":true,"_enabled":true,"_busy":false,"_ignoreFocusOut":true,"_value":"","_buttons":[{"iconPath":{"dark":{"$mid":1,"path":"/c:/Users/Kleber/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.6.0/third-party/resources/from-vscode-icons/dark/refresh.svg","scheme":"file"},"light":{"$mid":1,"path":"/c:/Users/Kleber/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.6.0/third-party/resources/from-vscode-icons/light/refresh.svg","scheme":"file"}},"tooltip":"Refresh skills"}],"_handlesToButtons":{},"_onDidAcceptEmitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},"_onDidChangeValueEmitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},"_onDidTriggerButtonEmitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},"_onDidHideEmitter":{"_disposed":false},"_pendingUpdate":{"id":3},"_disposed":false,"_disposables":[{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},{"_disposed":false},{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},{"_disposed":false},{"_disposed":false}],"_items":[],"_handlesToItems":{},"_itemsToHandles":{},"_canSelectMany":false,"_matchOnDescription":true,"_matchOnDetail":true,"_sortByLabel":true,"_activeItems":[],"_onDidChangeActiveEmitter":{"_disposed":false},"_selectedItems":[],"_onDidChangeSelectionEmitter":{"_disposed":false},"_title":"All skills"}]
[verbose - 2021-07-01 11:35:55.203Z] Calling method: ask.container.viewAllSkills.calculateTimeExceedHourly, args: [1625138813340,1625139355203,1]
[verbose - 2021-07-01 11:35:55.203Z] Calling method: ask.container.viewAllSkills.setQPItems, args: [{"_extensionId":{"value":"ask-toolkit.alexa-skills-kit-toolkit","_lower":"ask-toolkit.alexa-skills-kit-toolkit"},"_id":3,"_visible":true,"_expectingHide":true,"_enabled":true,"_busy":false,"_ignoreFocusOut":true,"_value":"","_buttons":[{"iconPath":{"dark":{"$mid":1,"path":"/c:/Users/Kleber/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.6.0/third-party/resources/from-vscode-icons/dark/refresh.svg","scheme":"file"},"light":{"$mid":1,"path":"/c:/Users/Kleber/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.6.0/third-party/resources/from-vscode-icons/light/refresh.svg","scheme":"file"}},"tooltip":"Refresh skills"}],"_handlesToButtons":{},"_onDidAcceptEmitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},"_onDidChangeValueEmitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},"_onDidTriggerButtonEmitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},"_onDidHideEmitter":{"_disposed":false},"_pendingUpdate":{"id":3},"_disposed":false,"_disposables":[{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},{"_disposed":false},{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}},{"_disposed":false},{"_disposed":false}],"_items":[],"_handlesToItems":{},"_itemsToHandles":{},"_canSelectMany":false,"_matchOnDescription":true,"_matchOnDetail":true,"_sortByLabel":true,"_activeItems":[],"_onDidChangeActiveEmitter":{"_disposed":false},"_selectedItems":[],"_onDidChangeSelectionEmitter":{"_disposed":false},"_title":"All skills"}]
[verbose - 2021-07-01 11:35:55.203Z] Calling method: getCachedSkills, args: [null]
[verbose - 2021-07-01 11:35:55.203Z] Calling method: getSkillNameFromLocales, args: [{"pt-BR":"cake time"},null]
[error - 2021-07-01 11:35:55.219Z] Telemetry is disabled. Not uploading any data.. 

[verbose - 2021-07-01 11:35:56.853Z] Calling method: getSkillMetadata, args: ["amzn1.ask.skill.189f96d7-93b1-4cc3-bab1-b77d10e046f7","development"]
[debug - 2021-07-01 11:35:57.103Z] Calling method: askContainer.skillsConsole.cloneSkill, args:  [{"data":{"skillSummary":{"_links":{"self":{"href":"/v1/skills/amzn1.ask.skill.189f96d7-93b1-4cc3-bab1-b77d10e046f7/stages/development/manifest"}},"apis":["custom"],"lastUpdated":"2021-06-22T18:42:41.075Z","nameByLocale":{"pt-BR":"cake time"},"publicationStatus":"DEVELOPMENT","skillId":"amzn1.ask.skill.189f96d7-93b1-4cc3-bab1-b77d10e046f7","stage":"development"},"hostedSkillMetadata":{"alexaHosted":{"repository":{"type":"GIT","url":"https://git-codecommit.us-east-1.amazonaws.com/v1/repos/189f96d7-93b1-4cc3-bab1-b77d10e046f7"},"runtime":"python3.7"}},"isHosted":true},"label":"amzn1.ask.skill.189f96d7-93b1-4cc3-bab1-b77d10e046f7"}]
[verbose - 2021-07-01 11:35:57.103Z] Calling method: createSkillFolder 
[verbose - 2021-07-01 11:36:05.536Z] Calling method: getSkillNameFromLocales, args: [{"pt-BR":"cake time"},null]
[debug - 2021-07-01 11:36:05.536Z] Skill folder d:\Projetos Outros\Alexa\caketime already exists. 
[debug - 2021-07-01 11:36:08.197Z] Confirmed skill folder overwrite option. Overwriting d:\Projetos Outros\Alexa\caketime. 
[verbose - 2021-07-01 11:36:08.210Z] Calling method: cloneSkill, args:  [{"_proxy":{},"_handle":2}]
[verbose - 2021-07-01 11:36:08.210Z] Calling method: checkGitInstallation 
[verbose - 2021-07-01 11:36:08.210Z] Calling method: isGitInstalled 
[verbose - 2021-07-01 11:36:08.210Z] Executing git command : git --version 
[verbose - 2021-07-01 11:36:08.701Z] Calling method: setupGitFolder 
[verbose - 2021-07-01 11:36:09.050Z] Calling method: downloadGitCredentialScript, args:  ["d:\\Projetos Outros\\Alexa\\caketime"]
[verbose - 2021-07-01 11:36:09.052Z] Executing git command : git init "d:\Projetos Outros\Alexa\caketime" --quiet 
[verbose - 2021-07-01 11:36:09.470Z] Executing git command : git config --local credential.https://git-codecommit.us-east-1.amazonaws.com/v1/repos/189f96d7-93b1-4cc3-bab1-b77d10e046f7.helper "" 
[verbose - 2021-07-01 11:36:09.890Z] Executing git command : git config --local --add credential.https://git-codecommit.us-east-1.amazonaws.com/v1/repos/189f96d7-93b1-4cc3-bab1-b77d10e046f7.helper "!'C:\Users\Kleber\.ask\scripts\git-credential-helper' default amzn1.ask.skill.189f96d7-93b1-4cc3-bab1-b77d10e046f7" 
[verbose - 2021-07-01 11:36:10.313Z] Executing git command : git config --local credential.https://git-codecommit.us-east-1.amazonaws.com/v1/repos/189f96d7-93b1-4cc3-bab1-b77d10e046f7.UseHttpPath true 
[verbose - 2021-07-01 11:36:10.747Z] Executing git command : git remote add origin https://git-codecommit.us-east-1.amazonaws.com/v1/repos/189f96d7-93b1-4cc3-bab1-b77d10e046f7 
[verbose - 2021-07-01 11:36:11.173Z] Calling method: getOrInstantiateGitApi 
[error - 2021-07-01 11:36:54.445Z] Git folder setup failed for d:\Projetos Outros\Alexa\caketime. Reason: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "AuthenticationFailed",
  "gitCommand": "fetch",
  "stdout": "",
  "stderr": "warning: invalid credential line: Failed to fetch a LWA access token.\nfatal: Authentication failed for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/189f96d7-93b1-4cc3-bab1-b77d10e046f7/'\n"
} 

[error - 2021-07-01 11:36:54.459Z] Telemetry is disabled. Not uploading any data.. 

[error - 2021-07-01 11:36:54.460Z] Skill clone failed. Reason: Git folder setup failed for d:\Projetos Outros\Alexa\caketime. Reason: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "AuthenticationFailed",
  "gitCommand": "fetch",
  "stdout": "",
  "stderr": "warning: invalid credential line: Failed to fetch a LWA access token.\nfatal: Authentication failed for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/189f96d7-93b1-4cc3-bab1-b77d10e046f7/'\n"
} 

[error - 2021-07-01 11:36:54.461Z] Telemetry is disabled. Not uploading any data..

**Comment by Shreyas-vgr** [comment]
Hi @krsmga , are you still the issue on the latest VSCode extension?
