### ISSUE TITLE
ask init -l option not supported

### ISSUE THREAD

**Issue by VLH-max** [alexa/ask-toolkit-for-vscode#14]
It seems the extension used to work with an old version of ASK CLI.
I have ASK CLI 2.0 and when I try to use the VSCode extention I always get an error message saying "ask init -l option is not supported" 

Indeed that option doesn't exist.
Everything works fine when I use ASK CLI directly (I can deploy,...)

**Comment by VLH-max** [comment]
In fact if I refer to this:
https://developer.amazon.com/fr-FR/docs/alexa/ask-toolkit/get-started-with-the-ask-toolkit-for-visual-studio-code.html

I assume most commands in the ASK Toolkit for VSCode won't work anymore, since they're mapped to obsolete ASK CLI commands.

Should I install an older version of ASK CLI?

**Comment by nikhilym** [comment]
Hi @VLH-max , sorry for the inconvenience. Your guess is right. The `v2` version of `ASK CLI` has many commands moved, and they no longer interop well with the plugin. Please downgrade the CLI version to `v1`, if you are using it through the plugin. 

Thanks for pointing out the doc. We are working with the doc team to get it updated.

**Comment by VLH-max** [comment]
Indeed, downgraded to 1.7.23 and working like a charm.
Thanks for the quick reply!
