### ISSUE TITLE
how to change default profile selected in ASK PROFILE in VScode. How to sign in again with different account

### ISSUE THREAD

**Issue by rimishagupta28** [alexa/ask-toolkit-for-vscode#146]
**Desktop (please complete the following information):**

-   OS:
-   VS Code version:
-   Alexa Skill Toolkit extension version:

**Question**

**Comment by Shreyas-vgr** [comment]
Hi @rimishagupta28, to change default profiles in VSCode.
You can select the ASK Profile widget on the status bar displayed at the bottom of the VsCode IDE.
Example reference

![Screen Shot 2021-09-27 at 11 46 28 AM](https://user-images.githubusercontent.com/3158685/134967295-2ebf9e3c-c340-4172-aac1-2f62a4444035.png)

You can also open Profile manager (command: cmd + Shift+ P) in MacOS which helps you create new profile and also delete existing profiles.
