### ISSUE TITLE
I cannot register my device to use the device simulator in VSCode

### ISSUE THREAD

**Issue by jasontaylor190** [alexa/ask-toolkit-for-vscode#152]
I cannot register my device to use the device simulator in VSCode

**Extension Logs**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS:
-   Visual Studio Code Version:
-   Alexa Skill Toolkit Version:

**Additional context**

**Comment by sjcomstock67** [comment]
@jasontaylor190 - is this still an issue? can you provide more details on the steps followed?

**Comment by Shreyas-vgr** [comment]
Hi @jasontaylor190, can you provide more details to re-produce the issue if it still exits on the latest version.
