### ISSUE TITLE
I've downloaded an existing skill, how do I connect to my remote dynamodb when debugging locally

### ISSUE THREAD

**Issue by TommyBs** [alexa/ask-toolkit-for-vscode#155]
**How do I configure my skill to use my dynamodb table when testing locally.**

First time I've tried using this extension for VS code. I downloaded an existing skill of mine, but when I try to run it I get the following error:

`Uncaught AskSdk.DynamoDbPersistenceAdapter Error: Could not create table (tablename): Missing region in config`

Can the docs explain how we should set this up? I don't know what config this is referring to. A region is specified in my launch.json 

I can call `AWS.config.update({region:'region'});` in my code but then this falls the wrong thing to do if I want dynamodb tables in multiple regions. I also then get an error about  missing credentials in the config file.

I've found one other issue that references this error but it was closed due to inactivity and no one ever commented on it. I've not used the CLI before, so not sure if I'm missing any additional setup other than installing this plugin and signing in

**Comment by sjcomstock67** [comment]
Hi @TommyBs - We've had some team turnover. Can have @Shreyas-vgr or @sam-goodwin take a look once back from OOTO.
