### ISSUE TITLE
Can't Download Skill into VS Code

### ISSUE THREAD

**Issue by winghavenrc** [alexa/ask-toolkit-for-vscode#169]
I'm getting this error when I try to Dowload a skill from the web ASK Developer Console into VSCode using the ASK Extension:
Skill clone failed. Reason: Git folder setup failed for c:\Users\NAME\MedicationsCheckup. Reason: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "CantAccessRemote",
  "gitCommand": "fetch",
  "stdout": "",
  "stderr": "C:\\Users\\NAME\\.ask\\scripts\\git-credential-helper: line 1: syntax error near unexpected token `newline'\nC:\\Users\\NAME\\.ask\\scripts\\git-credential-helper: line 1: `<?xml version=\"1.0\" encoding=\"UTF-8\"?>'\nfatal: unable to access 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/92b21708-d05c-4a3e-896a-373c263291c9/': The requested URL returned error: 403\n"
}

Even though I've created a Profile which required me to sign-in to my Alexa Dev account successfully, the extension challenges me for my username and password - which I am positive I've entered correctedly.  However, it always throws this error.

I've reloaded the ASK extension several times and even re-installed VSCode but nothing has resolved this.

Thanks

**Comment by Ari6** [comment]
What version of VSCode are you using? I had the same issue on Mac OS 12.2.1. I updated VSCode to 1.65 and the issue was fixed.
