### ISSUE TITLE
Cannot install in VSCodium

### ISSUE THREAD

**Issue by jonmadison** [alexa/ask-toolkit-for-vscode#19]
**Describe the bug**

Can't install ASK to vscodium

**To Reproduce**
1. Install vscodium
2. Go to install extensions and search -- it's not found
3. Alternately, go to the install page for the extension: https://marketplace.visualstudio.com/items?itemName=ask-toolkit.alexa-skills-kit-toolkit
4. right click install button and choose "copy link address"
5. change "vscode:" to "vscodium:" and hit enter
6. It opens vscodium but is a no-op

**Extension Logs**

**Expected behavior**

Installer for ASK shows up in IDE

**Screenshots**

**Desktop (please complete the following information):**

-   OS: OSX
-   Visual Studio Code Version: VSCodium
-   Alexa Skill Toolkit Version: latest

**Additional context**

**Comment by nikhilym** [comment]
Hey @jonmadison , looks like VSCodium has a [bug w.r.t fetching extensions from marketplace](https://github.com/VSCodium/vscodium/issues/418). I followed the workaround as mentioned [here](https://github.com/VSCodium/vscodium/issues/418#issuecomment-659257713) , restarted VSCodium and could get the extension installed and working as expected. Can you please try that and let us know if you still face any issue?

Here is my workstation details (from running the `> Alexa : About Alexa Skills Toolkit ` command from command palette, after installing the extension)

OS: Darwin x64 18.7.0
Visual Studio Code Version:  1.47.2
Alexa Skills Toolkit Version: 2.0.0
Git Version: git version 2.23.0

**Comment by nikhilym** [comment]
Hey @jonmadison , hope the issue has been resolved for you. Closing this because of no response. Please reopen if you still face issues. Thanks.
