### ISSUE TITLE
error at sign in 

### ISSUE THREAD

**Issue by gito333** [alexa/ask-toolkit-for-vscode#191]
**Desktop (please complete the following information):**

-   OS: Windows 10 21H2
-   VS Code version: 1.69
-   Alexa Skill Toolkit extension version: 2.22.2

**Question**
Im new to this and i have never done something similar so Im a little bit noob.
When I click in sign in, it redirects me to this page. I have already added my local adress to the developers configuration 

400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
Request Details
redirect_uri=http://localhost:9090/cb
scope=alexa::ask:skills:readwrite%20alexa::ask:models:readwrite%20alexa::ask:skills:test%20alexa::ask:catalogs:read%20alexa::ask:catalogs:readwrite%20alexa::ask:skills:debug
state=Ask-SkillModel-ReadWrite
response_type=code

**Comment by doiron** [comment]
Are you doing remote debugging by any chance?  Could you confirm if you have configured port forwarding to port 9090.   here's the FAQ that talks about this a bit. 

https://github.com/alexa/ask-toolkit-for-vscode#faqs

**Comment by doiron** [comment]
also if that doesn't help try to downgrade one version and let me know if that works. 

I presume you are on 2.11.2  ( not 2.22.2 )   try downgrading to 2.11.1.  

The little gear icon menu for the plugin has a "Install another version" option. 

  Image from https://code.visualstudio.com/  ![here](https://code.visualstudio.com/assets/docs/editor/extension-marketplace/uninstall-extension.png)

**Comment by isaiaszmendes** [comment]
Hello, @doiron, thank you for support!
This happend in my first alexa skill project, so I didn't configured the settings. When I did downgrade for 2.11.1 version, the sign in worked.
I did reset the settings before downgrade for test your solution, but it still did'n work

**Comment by doiron** [comment]
thanks for letting me know.  In that case I presume this [PR-164](https://github.com/alexa/ask-toolkit-for-vscode/pull/164) is the issue. We'll need to dive a bit into the issue and why it wasn't caught by the tests, fix and/or rollback.   Will update this issue once we have a more permanent fix.   Bu

**Comment by gito333** [comment]
> also if that doesn't help try to downgrade one version and let me know if that works.
> 
> I presume you are on 2.11.2 ( not 2.22.2 ) try downgrading to 2.11.1.
> 
> The little gear icon menu for the plugin has a "Install another version" option.
> 
> Image from https://code.visualstudio.com/ ![here](https://camo.githubusercontent.com/875c7357a096e3fecf4f0cd03c5fb73ce7b80086ed180b3fafb5f144e7694dee/68747470733a2f2f636f64652e76697375616c73747564696f2e636f6d2f6173736574732f646f63732f656469746f722f657874656e73696f6e2d6d61726b6574706c6163652f756e696e7374616c6c2d657874656e73696f6e2e706e67)

it was just that, i just tried by downgrading to 2.11.1 and it fixed it. Thanks you for your quick response

**Comment by tydonelson** [comment]
@gito333 @isaiaszmendes 

Thanks for your patience around this bug! We've reverted the change for now with this PR: https://github.com/alexa/ask-toolkit-for-vscode/pull/193

You can continue to use the latest version again, the current version as of now should be 2.11.3.
