### ISSUE TITLE
Problem to sign in my browser

### ISSUE THREAD

**Issue by andrecrjr** [alexa/ask-toolkit-for-vscode#192]
-   OS: Windows 10 x64
-   VS Code version: 1.69.1
-   Alexa Skill Toolkit extension version: v2.11.2

I'm getting a problem with sign in connection into amazon in alexa skills vscode:

![image](https://user-images.githubusercontent.com/7965520/179108667-b5d0cbd2-fcd0-4492-a2b9-964cc0e68aa9.png)

I don't know the url changes to localhost:9090 and then dont continue i get the screen above! I already put the redirect URI in web settings on my amazon developer account but nothing happened...

**Comment by tydonelson** [comment]
Hi @andrecrjr ,

Sorry you're running into this! We are aware of it and working to fix it, it's an issue that was introduced in 2.11.2. In the meantime, could you rollback to 2.11.1, per the instructions [here](https://github.com/alexa/ask-toolkit-for-vscode/issues/191#issuecomment-1184663090)?

**Comment by tydonelson** [comment]
Thanks for your patience around this bug! We've reverted the change for now with this PR: https://github.com/alexa/ask-toolkit-for-vscode/pull/193

You can continue to use the latest version again, the current version as of now should be 2.11.3.

**Comment by tydonelson** [comment]
Fixed via https://github.com/alexa/ask-toolkit-for-vscode/pull/193
