### ISSUE TITLE
Unable to receive events for Reminders/Skill enable or disable for Alexa Hosted Skill

### ISSUE THREAD

**Issue by mthakre** [alexa/ask-toolkit-for-vscode#209]
**Desktop (please complete the following information):**

-   OS: MacOS
-   VS Code version: 1.72.2
-   Alexa Skill Toolkit extension version: 2.28.0

**Question**
I have an Alexa hosted skill that sets a simple reminder at this point (skill id: `amzn1.ask.skill.bc36ba37-4960-4e47-9c61-35c3879f0be1`) . I have configured the skill manifest to receive events for various Reminder events like `REMINDER_CREATED`, `REMINDER_STATUS_CHANGED` etc. and also `SKILL_ENABLED`, `SKILL_DISABLED`.

When debugging with VSCode, I am able to see all the requests and responses for `IntentRequest`s. However I do not get any responses when the reminder is created or starts playing on a device. 

I wonder if this has to do with the auto configured lambda v/s provisioning your own aws lambda function.

Please let me know what can be done so that I get the events in VSCode when the reminder is created, started or ended.

```json
{
  "manifest": {
    "apis": {
      "custom": {
        "endpoint": {
          "uri": "arn:aws:lambda:us-east-1:581234951709:function:bc36ba37-4960-4e47-9c61-35c3879f0be1:Release_0"
        },
        "interfaces": [],
        "regions": {
          "EU": {
            "endpoint": {
              "uri": "arn:aws:lambda:eu-west-1:581234951709:function:bc36ba37-4960-4e47-9c61-35c3879f0be1:Release_0"
            }
          },
          "NA": {
            "endpoint": {
              "uri": "arn:aws:lambda:us-east-1:581234951709:function:bc36ba37-4960-4e47-9c61-35c3879f0be1:Release_0"
            }
          },
          "FE": {
            "endpoint": {
              "uri": "arn:aws:lambda:us-west-2:581234951709:function:bc36ba37-4960-4e47-9c61-35c3879f0be1:Release_0"
            }
          }
        }
      }
    },
    "manifestVersion": "1.0",
    "permissions": [
      {
        "name": "alexa::alerts:reminders:skill:readwrite"
      },
      {
        "name": "alexa::devices:all:notifications:write"
      },
      {
        "name": "alexa::async_event:write"
      }
    ],
    "events": {
      "endpoint": {
        "uri": "arn:aws:lambda:us-east-1:581234951709:function:bc36ba37-4960-4e47-9c61-35c3879f0be1:Release_0"
      },
      "regions": {
        "NA": {
          "endpoint": {
            "uri": "arn:aws:lambda:us-east-1:581234951709:function:bc36ba37-4960-4e47-9c61-35c3879f0be1:Release_0"
          }
        }
      },
      "subscriptions": [
        {
          "eventName": "REMINDER_CREATED"
        },
        {
          "eventName": "REMINDER_STARTED"
        },
        {
          "eventName": "REMINDER_STATUS_CHANGED"
        },
        {
          "eventName": "SKILL_ENABLED"
        },
        {
          "eventName": "SKILL_DISABLED"
        }
      ]
    },
    "publishingInformation": {
      "distributionCountries": [],
      "isAvailableWorldwide": true,
      "locales": {
        "en-US": {
          "description": "Sample Full Description",
          "examplePhrases": [
            "Alexa open nagging reminders"
          ],
          "keywords": [],
          "name": "Nagging Reminders",
          "summary": "Sample Short Description"
        }
      },
      "testingInstructions": "Sample Testing Instructions."
    }
  }
}
```

**Comment by tydonelson** [comment]
Hey Mahesh! Sorry for the delay in getting back here - I'm not sure exactly what's going on here yet, the thing that comes to mind is to try registering a virtual device in VSCode with the instructions under "How can I test APL user events and audio output in simulator?" in the FAQ - https://github.com/alexa/ask-toolkit-for-vscode#faqs

I know the instructions are specific to APL, but it might also be a way to forward these device notifications. If that doesn't have an effect, let me know and we can work on trying to get a smaller representative skill sample we can run and analyze in-house.
