### ISSUE TITLE
Error while trying to register a device for skill testing in VS Code

### ISSUE THREAD

**Issue by appcloid** [alexa/ask-toolkit-for-vscode#227]
I was setting up development and testing of Alexa Hosted skill in Visual Studio Code and was following this document - https://developer.amazon.com/de-DE/docs/alexa/ask-toolkit/vs-code-testing-simulator.html

When I tried to register a device for testing I got following error -

_Error running command askContainer.skillsConsole.deviceRegistry: Cannot read properties of undefined (reading 'CommandType'). This is likely caused by the extension that contributes askContainer.skillsConsole.deviceRegistry._

**To Reproduce**

1. Go to 'Skills Management'
2. Click on ellipsis (…) 
3. Click on 'Register Device'
5. Tried the same after closing and opening the Visual Code
6. Open `ASK Toolkit` Output window, and provide the logs - No logs printed
7. When tried other options under Skills Management like Profile Manager then a new error was shown -

_Error running command ask.init: Cannot read properties of undefined (reading 'CommandType'). This is likely caused by the extension that contributes ask.init._

**Context**
-   OS: Windows 10
-   Visual Studio Code Version: 1.74.0
-   Alexa Skill Toolkit Version:

**Additional context**

**Comment by doiron** [comment]
Can you try to reach the page using keyboard shortcuts?  for mac I used "Command+Shift+P"   I believe something in the new VSCode version has caused this.

**Comment by doiron** [comment]
for windows I believe it's  ```ctrl + shift + p``` 

once you are in the Command palette, run 
```>Register device```

**Comment by tydonelson** [comment]
Closing for now, @appcloid if the above workaround doesn't work for some reason, please let us know and we can reopen.
