### ISSUE TITLE
Not able to hook local simulator or ask-cli simulator to the local debugger

### ISSUE THREAD

**Issue by mohammedalnuaimi** [alexa/ask-toolkit-for-vscode#229]
**Describe the bug**
I'm not able to debug Alexa Skill from ask-cli using ask dialog against the local setup debugger using "ask-sdk-local-debug" package
Worth mentioning I also can't trigger the debugger from the local simulator that comes with the Alexa Skill Toolkit extension
I appreciate your assistance

See above
**To Reproduce**

**Extension Logs**
No helpful logs generated

**Expected behavior**
I expect the degugger will be trigger when invoking the skill from the ask dialog or local simulator 

**Screenshots**

**Desktop (please complete the following information):**

-   OS: MacOS
-   Visual Studio Code Version:Version: 1.45.1
-   Alexa Skill Toolkit Version: 2.4.0

**Additional context**

**Comment by mohammedalnuaimi** [comment]
Thanks @tydonelson yes I have followed this setup and even surfed the web to see if I have done something differently but couldn't find the reason, and yes I get the same as what in the above screen shots, there is no bug or errors, it's only the local simulator not triggering the debugger!

**Comment by tydonelson** [comment]
Hey @mohammedalnuaimi , couple more things you could check - 

What region is specified for the skill debug session? Does that match the region where your skill is deployed?

**Comment by mohammedalnuaimi** [comment]
Thanks @tydonelson I have tried the three regions in the launch.json and getting the same result!

**Comment by mohammedalnuaimi** [comment]
The issue is the local debugger has to be triggered in a particular way before sending an invocation, so after pressing the debugger to run, I have to press continue couple of times to see further information about the debugger session time and the region, and then sending an utterance through the local simulator, at this point the debugger intercept the call
