### ISSUE TITLE
Local debugging not working

### ISSUE THREAD

**Issue by ra-hardy** [alexa/ask-toolkit-for-vscode#25]
**Desktop (please complete the following information):**

```
OS: Linux x64 5.4.40-04224-g891a6cce2d44
Visual Studio Code Version:  1.47.3
Alexa Skills Toolkit Version: 2.0.0
Git Version: git version 2.27.0
```

**Question**

Summary: Lambda skill runs locally in VS Code but I can't get the console to invoke it

I have the following set up:
1.  A UK dev account.  I then followed the instructions to create a US dev account and linked them
2. Signed into the ASK Toolkit using the US dev account with the profile named 'default'
3. The skill was originally created in the UK dev account console. I've downloaded/cloned it using the Toolkit  using the 'default' profile (this was slightly complex, as I had to create a UK profile to get the skill to be listed as available to download, then switch to the 'default' profile to download it)
4. I've followed the instructions for local debugging, and see the "*****Starting Skill Debug Session in NA region*****" message with the ws: URL

So that's all good.

Back in the console, I have logged in using the US account.  I try and run the skill, but it always uses the hosted version and not the local one. 

This worked at one point earlier today and yesterday, as I was successfully invoking the skill locally.  I've changed something - not sure what - and now can't get it to invoke locally.  So I've tried reinstalling the Toolkit, deleting the ~/.ask directory and recreating the 'default' profile, and downloading a fresh copy of the skill.

Is there anything else I can try and do to get this working?

**Comment by sattpat** [comment]
Thanks for reporting this issue @ra-hardy . 
Could you tell me the skill ids being used in US and UK. And also could you also provide the timestamp for a request that you are making for on the skill being used under the US accounts?

**Comment by ra-hardy** [comment]
Skill ID for the UK skill is amzn1.ask.skill.17be92cf-6a62-48db-8a69-2dde06381b60
I only have a UK skill in this case.

I made a request a moment ago, so the timestamp in the console is 19:00:44:431 UK time.

**Comment by sattpat** [comment]
@ra-hardy your skill requests are still being routed to eu-west-1. Would it be possible for you to log out from the dev console for both EU and NA accounts, log back into the NA account and start a new Test session?

**Comment by ra-hardy** [comment]
Ok, I've logged out of both accounts. I cleared my cache/cookies in case that makes a difference. Logged back into the US one.  Started a new test session, but it is invoking the hosted skill.  (I've just realised I can see the API endpoint in the JSON input, which is still EU)

**Comment by ra-hardy** [comment]
I found a workaround.  I created a second US account and linked that to the UK account.  I created a US skill in the console and tested that, hoping that this might initialise everthing properly.  I can see in the console the endpoint invoked isn't the EU one.   Created a new profile called 'default2' using the new US account, and modified ask-resources.json to change it to default2.  This time, it's working.  So, I'm not sure what happened to the first US account, and whether the problem will re-occur.  But at least I've found a workaround.

**Comment by sattpat** [comment]
That's strange. Just to be clear, the profile - 'default' is the US account right?

**Comment by ra-hardy** [comment]
Yep, 'default' and the new 'default2' are US accounts

**Comment by sattpat** [comment]
Closing this issue as you are unblocked. Please reopen if the issue surfaces again.
