### ISSUE TITLE
"There is no interaction model for en-US. Select a different locale." 

### ISSUE THREAD

**Issue by cancastilho** [alexa/ask-toolkit-for-vscode#254]
**Describe the bug**

After creating a skill using the web browser, I've found the possibility of using vs code to edit the skill. Then, I've installed the vscode extension and did the necessary configuration so that I could start using it to develop a sample skill. But, the option Test Skill -> Open simulator was throwing me the error "There is no interaction model for en-US. Select a different locale.". That's ok, because when I've created the skill I selected Brazilian Portuguese as the default language. So, as sugested by the error message, I tried to change the locale in the locale combobox (show below), but I couldn't, because it was stuck with a "Loading...":

![image](https://user-images.githubusercontent.com/952143/230789245-39ca6acd-bf7b-4f82-931b-e1a75e3346c8.png)

**To Reproduce**

High level steps  to reproduce the behavior (of what I remember I've done so far, I have not tested it):
1. Create a custom skill using the web browser selecting as primary language Portuguese BR.
2. Add 3 more languages using web browser: English (US), Spanish (ES) and Spanish (US), but without their interaction model.
3. Install and configure VScode ASK extension.
4. Sign in using the extension.
5. Download the previously created skill using the option "Download and edit skill"
6. Install ask-sdk-local-debug for nodejs as described in the [README ](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-sdk-local-debug)
7. Configure the lauch.json as described [in the docs](https://developer.amazon.com/en-US/docs/alexa/ask-toolkit/vs-code-testing-simulator.html).
8. Use the option "Test Skill -> Open Simulator" to see the error. 

**Expected behavior**

The expected behaviour would be allowing me to select the Portuguese Language after the error is shown, even though the English model doesn't exist yet.

![image](https://user-images.githubusercontent.com/952143/230788897-542c135f-56ea-42f5-bb13-9e1d180a9a60.png)

**Desktop (please complete the following information):**

- OS: Windows_NT x64 10.0.19044
- Visual Studio Code Version:  1.77.1
- Alexa Skills Toolkit Version: 2.14.1
- Git Version: git version 2.35.1.windows.2

**Additional context**

As a workaround to solve the problem, I've added a en-US locale to the skill using the web browser, saved and deployed. I had to close the vscode an open it again. Then, in vscode, I downloaded the en-US locale json configuration using the option "Interaction model"-> Download. After that, the error stopped showing and I could select any of the 4 languages shown in the second image above.

**Comment by tydonelson** [comment]
@cancastilho Thanks for the detailed report Carlos! I'll take a look into what's going on.

**Comment by tydonelson** [comment]
To clarify, after you worked around the issue and were able to select Portuguese (BR), were you able to test your skill?

**Comment by cancastilho** [comment]
Yes, after the workaround I could use the simulator in  vscode to test the skill.



> To clarify, after you worked around the issue and were able to select Portuguese (BR), were you able to test your skill?

**Comment by doiron** [comment]
re-opening.   we pushed the changes but we are holding back the actual release until Monday. I'll comment again here and close once the release is out.

**Comment by doiron** [comment]
released 2.14.2 to VScode marketplace.  Let us know if the problem persists after updating. 

thank you for reporting the bug!
