### ISSUE TITLE
Extension not loading

### ISSUE THREAD

**Issue by ra-hardy** [alexa/ask-toolkit-for-vscode#36]
**Describe the bug**

This worked yesterday, but today, mysteriously, the Ask Toolkit extension isn't working at all in VS Code. The icon shows, and the skills management and documentation panels show but with no contents.  I've tried uninstalling and reinstalling the extension, with and without restarting VS Code.

**To Reproduce**

1. Load VS Code
2. Click the ASK icon

Observed: the two panels are empty

VS Code's debug logs show 'cannot find module'. See screenshot

**Screenshots**

![Screenshot 2020-09-03 at 14 27 33](https://user-images.githubusercontent.com/12749172/92122117-f8c8d000-edf2-11ea-9bed-b6446713d48e.png)

**Desktop (please complete the following information):**

The 'about Alexa skills toolkit' is present in the command palette, but has no output. The debug shows "Command 'Alexa: About Alexa Skill Toolkit' resulted in an error (command 'ask.aboutToolkit' not found)"

-   OS: Debian 10
-   Visual Studio Code Version: 1.48.2
-   Alexa Skill Toolkit Version: 2.0.1

**Comment by ra-hardy** [comment]
I've fudged a fix, edited ~/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.0.1/package.json line to point to "./dist/extension"

I guess this is a problem with the 2.0.1 release?

**Comment by nikhilym** [comment]
Thanks for pointing this out @ra-hardy . I was able to reproduce this issue but interestingly, when doing our local development before the release, this didn't come up. We will be working on the fix and releasing the patch asap.

For now, please downgrade to version `2.0.0` manually to unblock.

**Comment by nikhilym** [comment]
Hey @ra-hardy  , we just released the version [`2.0.2`](https://marketplace.visualstudio.com/items?itemName=ask-toolkit.alexa-skills-kit-toolkit) that fixes this issue. Please install the latest version and let us know if you are still facing any issues.

**Comment by ra-hardy** [comment]
thanks, works now 👍

**Comment by nikhilym** [comment]
Awesome, thanks for updating. Once again sorry for the inconvenience. Please let us know if you are facing any issues or have any feedback to share!!
