### ISSUE TITLE
Alexa Skill Toolkit 2.0.1 not loading in VSCode

### ISSUE THREAD

**Issue by AdrianAndronescu** [alexa/ask-toolkit-for-vscode#37]
**Describe the bug**

Alexa Skill Toolkit extension is not working in VSCode

**To Reproduce**

1. Go to 'Alexa Skill Toolkit extension'

**Extension Logs**

Activating extension 'ask-toolkit.alexa-skills-kit-toolkit' failed: Cannot find module 'c:\Users\username\.vscode\extensions\ask-toolkit.alexa-skills-kit-toolkit-2.0.1\out\src\extension'
Require stack:
- \AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- \AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- \AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

**Expected behavior**

Skill Management page to be displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/63401519/92122516-32ee9d80-ee04-11ea-9b41-d9ca9bd87bc9.png)

**Desktop (please complete the following information):**

-   OS:
-   Visual Studio Code Version: 1.48.2
-   Alexa Skill Toolkit Version: 2.0.1

**Additional context**

Alexa Skill Toolkit was working before and now after multiple re-installations still not loading into VSCode.
I also reinstall the ASK-SDK. Still no change.
\.vscode\extensions\ask-toolkit.alexa-skills-kit-toolkit-2.0.1\out folder is indeed missing.

**Comment by nikhilym** [comment]
Thanks for pointing this out @AdrianAndronescu  . I was able to reproduce this issue but interestingly, when doing our local development before the release, this didn't come up. We will be working on the fix and releasing the patch asap.

For now, please downgrade to version `2.0.0` manually to unblock. Sorry for the inconvenience.

**Comment by nikhilym** [comment]
Hey @AdrianAndronescu , we just released the version `2.0.2` : https://marketplace.visualstudio.com/items?itemName=ask-toolkit.alexa-skills-kit-toolkit that fixes this issue. Please install the latest version and let us know if you are still facing any issues.

**Comment by nikhilym** [comment]
Awesome, thanks for updating. Once again sorry for the inconvenience. Please let us know if you are facing any issues or have any feedback to share!!
