### ISSUE TITLE
Vscode not importing amazon alexa projects

### ISSUE THREAD

**Issue by tonygair** [alexa/ask-toolkit-for-vscode#46]
**Desktop (please complete the following information):**

-   OS: ubuntu 20
-   VS Code version: 1.49.3
-   Alexa Skill Toolkit extension version:2.1

**Question**
Projects in Amazon developer are not importable

the alexa projects I have in development on Amazon are not appearing when I try to import them into my VS code editor

**Comment by nikhilym** [comment]
Hey @tonygair , thanks for raising the issue. As mentioned in [our docs](https://developer.amazon.com/en-US/docs/alexa/ask-toolkit/vs-code-ask-skills.html#skill), we currently only support cloning of `Alexa-Hosted skills`. Can you please confirm if the alexa projects you are trying to import, are indeed Alexa-Hosted skills and not self hosted?

**Comment by tonygair** [comment]
thanks Nikhil, you put your finger on it. I have it downloading now. I only
have to get it to recognise the logging, and ask_sdk_core libraries :) now

**Comment by nikhilym** [comment]
Glad to know you got it working @tonygair . I am going ahead and closing this issue. Please let us know if you face any other problem with the toolkit or have any feedback to share 😄
