### ISSUE TITLE
everytime i open or try to create a skill in visual studio code v1.47.3 i get error Skill clone failed. Reason: Git folder setup failed Reason: Failed to execute git {   "exitCode": 1,   "gitCommand": "checkout",   "stdout": "",   "stderr": "error: pathspec 'prod' did not match any file(s) known to git\n" }

### ISSUE THREAD

**Issue by doctor-iksterog** [alexa/ask-toolkit-for-vscode#54]
**Describe the bug**

**To Reproduce**

**Extension Logs**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS:
-   Visual Studio Code Version:
-   Alexa Skill Toolkit Version:

**Additional context**

**Comment by nikhilym** [comment]
Hey @doctor-iksterog , thanks for raising the issue. It would be really helpful if you can fill up the issue template with additional details (like OS, toolkit version etc.) and provide some more details about the workspace/skill being opened. Also, can you try opening a new vscode session, without any skill folder and try to check if the extension is working as expected?

**Comment by nikhilym** [comment]
Hey @doctor-iksterog , any updates?

**Comment by SpellMender** [comment]
Bumping. I am having this same issue. I've also posted on #59 . Awaiting a resolution.

**Comment by doctor-iksterog** [comment]
amzn1.ask.skill.35f7722e-89ad-46ce-b5a9-054850a3d6d6

tried opening on clean open , nothing else open and same error. macos 10.15.6. happens on any existing skill i have. i have git 2.4.1
<img width="490" alt="Screen Shot 2020-11-14 at 8 04 10 PM" src="https://user-images.githubusercontent.com/63942278/99161992-73e11900-26b5-11eb-926c-58ecd8b2ba5a.png">

**Comment by SpellMender** [comment]
@doctor-iksterog Please see issue #59. We discovered a workaround. I even posted instructions with screenshots. Should be able to fix on Mac as well.

**Comment by nikhilym** [comment]
Please find the fix and the corresponding discussion regarding this issue on #59 . Closing this since the latest extension release v2.2.0 fixes this. Please update your extension and let us know if you still face issues. Thanks.
