### ISSUE TITLE
Local debugging fails with 401 error

### ISSUE THREAD

**Issue by s-maheshbabu** [alexa/ask-toolkit-for-vscode#64]
**Describe the bug**

I tried setting up local debugging following the instructions [here](https://developer.amazon.com/en-US/docs/alexa/ask-toolkit/vs-code-testing-simulator.html)
However, when I try to start the debugging session, I get a 401 error within VS Code.

**Important** If I fetch the accessToken myself using the command `ask util generate-lwa-tokens --scopes alexa::ask:skills:debug` and then start the local debugging session at the terminal using that access token, local debugging works. 
The inbuilt mechanism in VSCode is somehow fetching an invalid access token and failing with a 401.

**To Reproduce**

1. Follow the instructions [here](https://developer.amazon.com/en-US/docs/alexa/ask-toolkit/vs-code-testing-simulator.html) to setup local debugging.
2. Open the Run menu and then choose Start Debugging.
3. VS Code errors out with 401 code.

**Extension Logs**
See attached image.

-   OS: macOS Big Sur 11.0
-   Visual Studio Code Version: 1.51.1
-   Alexa Skill Toolkit Version: v2.2.0

<img width="1959" alt="Screen Shot 2020-11-20 at 12 52 52 PM" src="https://user-images.githubusercontent.com/10920089/99848863-643b5780-2b2f-11eb-885e-54ef81da8584.png">

**Comment by nikhilym** [comment]
Hey @s-maheshbabu , thanks for reporting this. I tried local debugging on my skill, through the extension on the following configuration and see that it is working as expected

OS: Darwin x64 19.6.0
Visual Studio Code Version:  1.51.1
Alexa Skills Toolkit Version: 2.2.0
Git Version: git version 2.29.2

Since you mention that by using the scoped access token from CLI, the local debug connection is getting set up correctly, I am guessing this has something to do with the profile you created in the extension. Can you recreate the profile through the `Profile Manager` in the extension, and check if local debugging works alright? You can navigate to the `Profile Manager` view by clicking on the options `...` tab on the `Skill Management` tree view in the extension

![Screen Shot 2020-11-20 at 1 06 36 PM](https://user-images.githubusercontent.com/25237515/99849958-5090f080-2b31-11eb-9be4-df6adb6dcf32.png)

Let us know if that works.

**Comment by s-maheshbabu** [comment]
No luck. I deleted the 'default' profile and recreated it and I still get the 401s.

I created a new profile within VC Code and I get an error like this - 
'ProfileName' profile doesn't have access to the skill. Please use 'default' profile..

**Comment by s-maheshbabu** [comment]
VC Code is fetching a valid looking access_token (starts with Atza|) but then fails when trying to actually connect.

**Comment by s-maheshbabu** [comment]
In case it helps with the investigation, I also get this false toast warning every once in a while in VS Code.
"This skill has not been previously deployed. Some extension functionalities will be unavailable until an initial deployment."

That is not true. The skill has been deployed multiple times using the extension. 

<img width="1959" alt="Screen Shot 2020-11-20 at 2 06 41 PM" src="https://user-images.githubusercontent.com/10920089/99854429-a6699680-2b39-11eb-8216-e9b969466995.png">

**Comment by sattpat** [comment]
> In case it helps with the investigation, I also get this false toast warning every once in a while in VS Code.
> "This skill has not been previously deployed. Some extension functionalities will be unavailable until an initial deployment."
> 
> That is not true. The skill has been deployed multiple times using the extension.
> 
> <img alt="Screen Shot 2020-11-20 at 2 06 41 PM" width="1959" src="https://user-images.githubusercontent.com/10920089/99854429-a6699680-2b39-11eb-8216-e9b969466995.png">

@s-maheshbabu so the skill has been deployed using the `default` profile and I suspect you are on the new profile that you created to use local debugging?



> No luck. I deleted the 'default' profile and recreated it and I still get the 401s.
> 
> I created a new profile within VC Code and I get an error like this -
> 'ProfileName' profile doesn't have access to the skill. Please use 'default' profile..

I just checked our logs and I see that the local debug scope is still missing from your permission list. And the fact that you are able to generate a token manually and use it proves that your account should be able to debug the skill. I understand that you deleted and created the `default` profile again? Can you verify that when you are firing the debugging session, you are on the `default` profile?

**Comment by s-maheshbabu** [comment]
I verified the following while trying to launch local debugging:

I get 401 errors using the 'default' profile on VSCode.
I get 'profile doesn't have access to the skill' error if I create a new profile within VS Code and use it. 
I get 'profile doesn't have access to the skill' error if I create a new profile at CLI (ask configure) and use it. 

Additional Info:
When using 'default' profile, I'm able to deploy the skill, test the skill etc. in VS Code.
When I create a new profile using 'Profile Manager', I only see APL. All other options disappear. The new profile is somehow not able to access the skill at all.

**Comment by sattpat** [comment]
@s-maheshbabu 

> I verified the following while trying to launch local debugging:
> 
> I get 401 errors using the 'default' profile on VSCode.
> I get 'profile doesn't have access to the skill' error if I create a new profile within VS Code and use it.
> I get 'profile doesn't have access to the skill' error if I create a new profile at CLI (ask configure) and use it.
> 
> Additional Info:
> When using 'default' profile, I'm able to deploy the skill, test the skill etc. in VS Code.
> When I create a new profile using 'Profile Manager', I only see APL. All other options disappear. The new profile is somehow not able to access the skill at all.
> 
> Here is an image with status bar to prove I'm using default profile.
> <img alt="Screen Shot 2020-11-20 at 3 00 56 PM" width="2000" src="https://user-images.githubusercontent.com/10920089/99857952-3fe87680-2b41-11eb-8fa4-9dc885dffeac.png">

Unfortunately, you can only access features using the same named profile(in your case that would be `default`) as the one you used to download/create the skill. 
I am sorry for the hassle, but it looks like the `default` profile doesnt have the permission scope - `alexa::ask:skills:debug`.
Can you do the following?
1. Create a new profile.
2. Use the new profile to download the skill again.
3. Run local debugging using the new profile.

**Comment by s-maheshbabu** [comment]
That worked. Thanks for your responsiveness. 

<hr />
Additional Info: <br/>

<br/>
When I created a new profile through VSCode and downloaded the skill, local debugging worked as expected. 
<br /><br/>
When I created a new profile at command line using 'ask configure', activate the new profile in VSCode and download the skill, I got 401s for local debugging.
<br /><br/>
So bottom line is that profiles created outside VSCode don't seem to be working in VSCode. Please see if you can reproduce that.

**Comment by sattpat** [comment]
> When I created a new profile through VSCode and downloaded the skill, local debugging worked as expected.
> 
> When I created a new profile at command line using 'ask configure', activate the new profile in VSCode and download the skill, I got 401s for local debugging.
> BTW, when I create profiles at CLI, I also get asked to link it with an AWS profile which I did. Profile creation via VSCode doesn't ask to link AWS profiles. May be this step is somehow screwing this up?
> 
Can you tell me what the version of your ask cli is?

**Comment by s-maheshbabu** [comment]
2.6.0.

Good point. Let me try to update it to the latest and see if I can still reproduce the issue.

**Comment by s-maheshbabu** [comment]
Once I upgrade to 2.20.0 everything works as expected. So, there is just some incompatibility with ask-cli 2.6.0 and earlier. 

Sorry for the churn and thanks for the help.

**Comment by nikhilym** [comment]
Awesome @s-maheshbabu . Glad you got it working. Closing this issue as resolved. Please let us know if you are facing any other issue with the extension or have any feature requests.
