### ISSUE TITLE
Video doesn't pause in VS Code test simulator

### ISSUE THREAD

**Issue by s-maheshbabu** [alexa/ask-toolkit-for-vscode#67]
**Describe the bug**

I built an APL document that has the [Video component](https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-video.html). When I issue a 'pause' directive, the video playback doesn't pause in the VS Code simulator. However, the same code works fine in the developer console simulator and the video pauses.

**To Reproduce**
APL Document would contain something like this -
```javascript
{
                "type": "Video",
                "id": "anIdentifier",
                "width": "100%",
                "height": "100%",
                "autoplay": true,
                "source": "any valid mp4 URL"
}
```

The 'pause' directive looks like this -
```javascript
{
  "directives": [
    {
      "type": "Alexa.Presentation.APL.ExecuteCommands",
      "token": "VideoPlayerViewToken",
      "commands": [
        {
          "type": "Sequential",
          "commands": [
            {
              "type": "ControlMedia",
              "componentId": "VideoPlayerId",
              "command": "pause"
            }
          ]
        }
      ]
    }
  ]
}
```

Start the playback of the video and then issue the pause command in VS Code simulator. The video will not pause.
Do the same in developer console simulator. Video will pause.

**Expected behavior**

Video playback controls should work in VS Code test simulator.

**Comment by nikhilym** [comment]
Hey @s-maheshbabu , thanks for raising the issue and sorry for not responding earlier. The local simulator in the toolkit currently doesn't support all APL directives and events. We understand this is not ideal and will result in broken DX for skill developers, and we are sorry for the inconvenience. 

We are already working on supporting the events and directives, and will keep the community posted once we get this fixed. I am changing this issue to a feature request and keeping it in the queue. Thanks.

**Comment by s-maheshbabu** [comment]
Commenting to make sure it won't get closed.

**Comment by wyajunjun** [comment]
Thanks @s-maheshbabu for raising this issue! Closed this as it's fixed in this PR: https://github.com/alexa/ask-toolkit-for-vscode/pull/102
