### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rekha0702** [alexa/ask-toolkit-for-vscode#7]
- Issue Type: `Performance`
- Extension Name: `alexa-skills-kit-toolkit`
- Extension Version: `1.0.1`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Rekha\ask-toolkit.alexa-skills-kit-toolkit-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ShenChen-Amazon** [comment]
Hi rekha,

Could you please provide us with C:\Users\Rekha\ask-toolkit.alexa-skills-kit-toolkit-unresponsive.cpuprofile.txt if it's available? We need the profiler file to do the research.

Or, if you can reproduce the slowdown, please follow this guide to find the cause: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions.

Thanks,
Shen
