### ISSUE TITLE
Singing out of ASK on VSC

### ISSUE THREAD

**Issue by Rangrom182** [alexa/ask-toolkit-for-vscode#72]
**Desktop (please complete the following information):**

-   OS: Windows_NT x64 10.0.19041
-   VS Code version: 1.51.1
-   Alexa Skill Toolkit extension version: 2.2.0

**Question**

How do I sign out of an Alexa dev account on the ASK in VS?

**Comment by Rangrom182** [comment]
Misunderstood. Figured it out.

**Comment by nikhilym** [comment]
Glad you got that working @Rangrom182
