### ISSUE TITLE
Debug - Silent failure with Python 3.9

### ISSUE THREAD

**Issue by paoloantinori** [alexa/ask-toolkit-for-vscode#78]
**Describe the bug**

While trying to run a debug profile, configured according to the documentation, debugger starts correctly, on Linux (Fedora 33) if the python runtime selected in the status bar is `python2.7` but fails silently if it's `python3.9`

**To Reproduce**

1. On Fedora 33 fully updated
2. Select Python 3.9 as runtime
3. Start the debug process
4. This is seen in the Terminal window: `cd /data/repo/github/personal/alexa_pumrus ; /usr/bin/env /bin/python /home/pantinor/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 34197 -- /data/repo/github/personal/alexa_pumrus/pumrus/lambda/lambda_function.py`
6. Nothing in  `ASK Toolkit` Output window, with log level set to debug

**Extension Logs**

No logs:

```
[info - 2021-01-04 13:02:41.487Z] Activating extension 
[info - 2021-01-04 13:11:09.785Z] log level changed to debug 
```

**Expected behavior**

Debug process to start correctly, just like with Python 2.7 is selected (or at least some verbose error message)

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Linux - Fedora 33
-   Visual Studio Code Version: 1.52.1
-   Alexa Skill Toolkit Version: v2.2.0

**Additional context**

Not running in a virtual_env. Python 2.7 seems to work, but fails not finding the module installed (since they are installed only for python 3)

**Comment by sattpat** [comment]
Thanks for creating the issue @paoloantinori . I will try my best to root cause this issue.
Have you installed the package ask-sdk-local-debug for the Python3.9 env?

**Comment by paoloantinori** [comment]
Hi, thank you!
Yes, I've installed that. As mentioned it worked if python2 was used but
not python3

**Comment by paoloantinori** [comment]
Hi, sorry I've realized that my previous assessment was not entirely correct.

Something is actually working but either I have the wrong expectations or something else is not working.

If I put a break point somewhere on my `lambda_function.py` default file and I invoke the `debug` command in VSCode the debugger actually stops on my breakpoints!

But I was expecting it to somehow hang and to leave the debugging session open, instead if I let it run, the process starts and debugging session is no longer active.

Is this expected?

Furthermore, if I interact with the Alexa Web Console to test my skill, I was expecting this to be somehow linked with my VSCode local process, and instead I can see no reaction at all.

I'm not using the `Alexa simulator in VS Code` since it seems not to be working (if I interact with the chat dialog it returns only `undefined`

Am I just having the wrong expectation on how this is supposed to work or am I really facing some technical issue here?

**Comment by paoloantinori** [comment]
Found my issue. VSCode was running the debug process with the wrong profile and I've never noticed. Sorry for all this noise =-/

**Comment by sattpat** [comment]
Glad you got it working!
