### ISSUE TITLE
Warning message "The toolkit requires ASK CLI to execute the commands" after installing the plugin

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-toolkit-for-vscode#8]
**Description:**
After installing the VS Code extension, VSCode shows a warning that `The toolkit requires ASK CLI to execute the commands`, but the ask-cli is installed and the $PATH includes where the CLI resides. The check of the existence of "ask" command line fails and thus blocks the usage of plugin. 

**Steps to reproduce the issue:**
1. Work on a skill project in VSCode and quit the application directly (cmd+q in MAC OS).
2. Re-open the plugin application directly, VSCode will open skill project where it's last time quited.
3. Warning message will display.
4. Re-open the project, plugin will work as normal.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac
**VS Code version**:
v1.33.1

**Comment by RonWang** [comment]
Checking with VSCode team to see how they manage the lifecycle of VSCode and its plugin when starting the application: https://github.com/Microsoft/vscode/issues/72235

**Comment by kenjdavidson** [comment]
Noticed this too, but it's due to ASK CLI v2 not having the `ask init -l` option anymore, it looks like it was removed in v0.8.0.  The documentation says it was moved to `ask configure -l` but that's not the case, it's just gone.

```
Activating extension 'ask-toolkit.alexa-skills-kit-toolkit' failed: ASK CLI is not functional. Command failed: /bin/sh -c ask init -l error: unknown option '-l' .
```

**Comment by nikhilym** [comment]
The new extension version is completely decoupled of ASK CLI. Please upgrade to the latest version and try the features out. Closing this issue for now since this is on an earlier version. Thanks.
