### ISSUE TITLE
Simulator - Issue with apl templae without a speak directive

### ISSUE THREAD

**Issue by paoloantinori** [alexa/ask-toolkit-for-vscode#82]
**Describe the bug**
I have a handler that generates a Response that includes both a simple (text only) APL template and a voice message.
The `Device Preview` view works fine and shows the correct rendering of the APL template.

The error occurs if I modify my handler and remove the `.speak()` invocation. In this case the `Device Preview` tab stops rendering the APL template.

When I test this in the test tab of the Alexa Console, I can get a visual output even if I do not include any Speak directive.

My specific use case is that of an APL template that uses the `SpeakList` command, so I do not need to add a speak directive (at least for the devices with a screen) 

**To Reproduce**

1. Write a simple handler that renders something visually with an APL template AND returns voice.
2. Verify that it works as expected in the simulator
3. Remove only the voice directive from the response
4. Verify that nothing gets rendered

**Extension Logs**

```
[error - 2021-01-09 17:14:35.676Z] The simulator did not respond to your request. Try again.. Reason: Simulation in progress. 
```

**Expected behavior**

Render just the visual output

**Screenshots**

![Screenshot from 2021-01-09 18-15-14](https://user-images.githubusercontent.com/1520602/104104170-b8002c80-52a6-11eb-86de-5ef0e67696df.png)

**Desktop (please complete the following information):**

-   OS: Linux Fedora 33
-   Visual Studio Code Version: 1.52.1
-   Alexa Skill Toolkit Version: 2.20.0

**Additional context**

**Comment by nikhilym** [comment]
Hey @paoloantinori , thanks for raising the issue. There seems to be two issues here : 

1. If there is no `outputSpeech` in response JSON, `device preview` in simulator doesn't show the response display.
2. `Simulation in progress` error for response containing `SpeakList` command.

I could reproduce the issue in (1), and it seems to be an issue on the `simulator` webview whenever the `outputSpeech` value is empty in the response JSON. We will take it as a bug and will look into fixing it.

(2) is a bit interesting. Can you please share your response JSON and APL document, that lead to this issue? I can try to check if that will reproduce this issue.

**Comment by nikhilym** [comment]
Hey @paoloantinori , can you share the APL document and the response JSON that you were trying to test with?

**Comment by paoloantinori** [comment]
Sure, but in afraid i won't be able to do it before the weekend. 

Thanks for looking into this!

**Comment by nikhilym** [comment]
No issues. Please update the ticket once you get a chance. Thanks.

**Comment by paoloantinori** [comment]
@nikhilym I can no longer replicate the second error, sorry!

Thank you very much for the support so far!
