### ISSUE TITLE
Alexa Debugging In VS Code: Process Exited With Code 255 (node js)

### ISSUE THREAD

**Issue by mlbhuvan** [alexa/ask-toolkit-for-vscode#84]
hi there, this is re issue earlier raised but was closed as there was no inactivity: https://github.com/alexa/ask-toolkit-for-vscode/issues/26

I'm getting the same error but for a similar scenario - I'm trying to debug Alexa on VS Code.
I tried changing the default shell to powershell but the issue still persisted.

Can I pls get some help on this one:

**Here is my launch.json file:**
{
"version": "0.2.0",
"configurations": [
{
"name": "Debug Alexa Skill (Node.js)",
"type": "node",
"request": "launch",
"program": "${command:ask.debugAdapterPath}",
"args": [
"--accessToken",
"${command:ask.accessToken}",
"--skillId",
"${command:ask.skillIdFromWorkspace}",
"--handlerName",
"handler",
"--skillEntryFile",
"${workspaceFolder}/lambda/index.js",
"--region",
"NA"
]
},

    {
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "skipFiles": [
            "<node_internals>/**"
        ],
        "program": "${file}"
    }
]
}

**this is the error I'm getting.**

"C:\Program Files\nodejs\node.exe" .\lambda\node_modules\ask-sdk-local-debug\dist\LocalDebuggerInvoker.js --accessToken Atza|IwEBIFrSQQ069MCMCUHSLNoClWR6tO9M2m8iix3GpNwVlAd2hMxu19-QDPo8QGiKIrLyKfY_0WATc-ytvAtaskFPTaZT1lX3c_Pcnxv-0IHtg8WlKteXZZCZgK7n8s_KeHVrc69SSqb9AdcuZVsRexOhghh3seGmDJ4sxkTTCheytojCZdKDDrLMPYrPjho9ISHuk1NJYXM_0XzyFnGtREoW0RdnEQ_euSGpWLO7rM3BOkvdKjtZdRKkKK0mTSIxsBvhvmH5pRx4sfeRuo-dS5QsHA3V2zr_STuFtNwLaWZMYjePAbknGIqqDHeAfn3K0zqqan3tht0LTYtXalQF01KW3kYpYOMYUFhzd3zU9VRk2MlNJkNZoocbZ9lhGefdmcPoNyQbVCvlJ1zIHbb5UKDBdEZRoWwKkZLEfq2Q9-kRURD5cbS9ksnTJo47_w6SCZb_yL-jYLudqkluGOGdvbH_gAIdcj6bPwjwdC4_YfER76XnKwOpoxb3MqKsHds8gofdDf563IruW6C84kw5PZw6-eFjXS0JMIGpTTM73L26jLuB43YX2_uMcXLyJYauqNSpzGraOgMJ74pfJQjqxKkbf-Iwd1LHvBb55ZZkofa7R66DaaR39kwwyV1V6ePanmGE524 --skillId amzn1.ask.skill.d47fd1a2-3e17-4df2-ab03-ab87e18229c2 --handlerName handler --skillEntryFile "C:\Users\aparn\OneDrive - Aiccelerate Consultancy Pty Ltd as Trustee\Business\Alexa\numbers app\numbersapp/lambda/index.js" --region NA

'IwEBIFrSQQ069MCMCUHSLNoClWR6tO9M2m8iix3GpNwVlAd2hMxu19-QDPo8QGiKIrLyKfY_0WATc-ytvAtaskFPTaZT1lX3c_Pcnxv-0IHtg8WlKteXZZCZgK7n8s_KeHVrc69SSqb9AdcuZVsRexOhghh3seGmDJ4sxkTTCheytojCZdKDDrLMPYrPjho9ISHuk1NJYXM_0XzyFnGtREoW0RdnEQ_euSGpWLO7rM3BOkvdKjtZdRKkKK0mTSIxsBvhvmH5pRx4sfeRuo-dS5QsHA3V2zr_STuFtNwLaWZMYjePAbknGIqqDHeAfn3K0zqqan3tht0LTYtXalQF01KW3kYpYOMYUFhzd3zU9VRk2MlNJkNZoocbZ9lhGefdmcPoNyQbVCvlJ1zIHbb5UKDBdEZRoWwKkZLEfq2Q9-kRURD5cbS9ksnTJo47_w6SCZb_yL-jYLudqkluGOGdvbH_gAIdcj6bPwjwdC4_YfER76XnKwOpoxb3MqKsHds8gofdDf563IruW6C84kw5PZw6-eFjXS0JMIGpTTM73L26jLuB43YX2_uMcXLyJYauqNSpzGraOgMJ74pfJQjqxKkbf-Iwd1LHvBb55ZZkofa7R66DaaR39kwwyV1V6ePanmGE524' is not recognized as an internal or external command,
operable program or batch file.

Process exited with code 255

**Comment by sattpat** [comment]
Closing this issue and reopening #26 as that thread has more context.
