### ISSUE TITLE
ASK Toolkit for VSCode - excessive "Failed to upload telemetry data" in logs

### ISSUE THREAD

**Issue by talkingnews** [alexa/ask-toolkit-for-vscode#97]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current Behavior

"Failed to upload telemetry data" appears in logs excessively. I don't have any outgoing ports blocked.

**NOTE** This is not an annoyance for me and I only see it if look in that window. However, if you are counting on this data to understand how many people are using it, then it will possibly be under-reporting.

## Steps to Reproduce (for bugs)

* Open ASK Toolkit for VSCode
* Go to ""Ask Toolkit" in Output window of VS Code.

## Your Environment

* ASK SDK for Node.js used: 2.22.4
* Operating System and version: Ubuntu 20.04

## Node.js and NPM Info
* Node.js version used for development: 14.15.4
* NPM version used for development:  7.5.2

**Comment by talkingnews** [comment]
Oh - thanks for that @nikhilym ! When I clicked "report a bug", it took me to the main ASK toolkit repo. I didn't know about this repo.

**Comment by nikhilym** [comment]
Hey @talkingnews , there seems to be an issue with the service team and we are tracking it. Good thing is, it doesn't affect the toolkit performance in any way. So skill developers should not see any issues w.r.t this. Thanks for letting us know this. We will update the issue once it is fixed from the service side.

**Comment by nikhilym** [comment]
Closing this bug since this has been resolved by the dependency service. Thanks @talkingnews once again, for reporting this issue.
